# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ucLE9Lt9tU1_mxSkZVwSB5GAWTlXNo4q
"""

import random
import string

nombre = ""
edad= ""
nif = ""

def generar_nif():
    numeros = ''.join(random.choices(string.digits, a=8))
    caracteres = ''.join(random.choices(string.ascii_uppercase,a=3))
    return f"{numeros}-{caracteres}"

def grabar_datos():
    global nombre, edad, nif
    nombre = input("Ingrese su nombre y apellido:")
    while len(nombre)<8 and len(nombre)> 20:
       print("el nombre debe tener almenos 8 letras de largo y menor de 20 letras")
       nombre= input("ingrese su nombre")
    print("Ingrese su edad, esta debe ser mayor a 0")
    edad= input()
    while not edad.isdigit() or int(edad)<=0:
        print("error la edad debe ser un número mayor a 0")
        edad= input()
    print("ingrese el nif de la persona")
    nif_valido= False
    while not nif_valido:
      print("el nif debe tener entre 4 y 12 caracteres")
      nif= input()
      if 5 <= len(nif) <=11:
        nif_valido=True
      else:
        print("el nif debe tener entre 4 y 12 caracteres")

    print("Sus datos fueron grabados exitosamente")
    print(f"nif:{nif}")

def buscar_por_nif():
    global nif
    print("Ingrese el NIF a buscar")
    nif = input()

    if True:
      print("La persona y sus NIF son correctos:" )
    else:
      print("La persona o su NIF no son correctos")
def imprimir_certificado_nacimiento():
    global nombre, edad, nif
    if nombre == "" or edad == "" or nif =="":
      print("Aún no se ingresan datos, vuelva e ingrese los datos")
      return
    estado_civil = random.choice(["soltero/a", "casado/a", "viudo/a", "divorciado/a"])


    print("*****Certificado de nacimiento*****")
    print(f"Nombre:{nombre}")
    print(f"NIF:{nif}")
    print(f"estado_civil: {estado_civil}")
    print("***********************************")

def MENU():
    while True:
        print("****MENU****")
        print("Bienvenido al menú de la identificación fiscal")
        print("escoja qué opción necesite")
        print("1. Grabar datos")
        print("2. Buscar a una persona")
        print("3. imprimir certificado")
        print("4. Salir")

        opc= input()

        if opc== "1":
          print("a escogido la opción 1, grabando datos")
          grabar_datos()
        elif opc=="2":
          print("a escogido la opción 2, buscando datos")
          buscar_por_nif()
        elif opc=="3":
          print("a escogido la opción 3, imprimiendo certificado")
          imprimir_certificado_nacimiento()
        elif opc=="4":
          print("saliendo del programa")
          break
        else:
          print("opción inválida, debe ser alguna de las primeras 4 opciones")

MENU()